# Generated by Django 3.0.7 on 2020-06-12 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardname', models.CharField(choices=[('sh', 'Shinhan'), ('km', 'Kookmin'), ('hn', 'Hana'), ('kkb', 'Kakaobank')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_credit', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
